version: '3'

server:
  command: "php artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8080 --workers=4 --max-requests=500"
  relay: pipes

http:
  address: "0.0.0.0:8080"
  middleware:
    - gzip
    - static
  static:
    dir: "public"
    forbid:
      - ".php"
      - ".htaccess"
  pool:
    num_workers: 4
    max_jobs: 500
    allocate_timeout: 60s
    destroy_timeout: 60s

logs:
  mode: production
  level: warn
  output: stdout
