[phases.setup]
  nixPkgs = ['...', 'php83', 'php83Extensions.pdo', 'php83Extensions.mbstring', 'php83Extensions.xml', 'php83Extensions.curl', 'php83Extensions.tokenizer', 'php83Extensions.zip', 'php83Extensions.redis']

[phases.install]
  cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build'
  ]

[phases.build]
  cmds = [
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
  ]

[start]
  cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT:-8080}'
