<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('sales', function (Blueprint $table) {
            $table->id();
            $table->foreignId('company_id')->constrained()->onDelete('cascade');
            $table->foreignId('product_id')->nullable()->constrained()->nullOnDelete();

            // Customer info (from WhatsApp conversation)
            $table->string('customer_name')->nullable();
            $table->string('customer_phone')->nullable();
            $table->string('customer_email')->nullable();

            // Product snapshot (at time of sale)
            $table->string('product_name');
            $table->string('product_sku')->nullable();
            $table->string('product_category')->nullable();
            $table->string('product_provider')->nullable(); // woocommerce, shopify, mercadolibre, manual

            // Transaction details
            $table->integer('quantity')->default(1);
            $table->decimal('unit_price', 12, 2);
            $table->decimal('total_price', 12, 2);
            $table->decimal('discount_amount', 12, 2)->default(0);
            $table->string('currency', 10)->default('USD');

            // Status tracking
            $table->enum('status', [
                'link_generated',  // Checkout link was generated
                'link_sent',       // Link was sent to customer via WhatsApp
                'completed',       // Sale confirmed/completed
                'cancelled',       // Sale cancelled
                'expired',         // Link expired without purchase
            ])->default('link_generated');

            // Source & context
            $table->enum('source', [
                'bot_whatsapp',    // Generated by bot via WhatsApp
                'manual',          // Manually entered by team
                'external',        // From external webhook/integration
            ])->default('bot_whatsapp');

            $table->string('checkout_url')->nullable();
            $table->string('conversation_id')->nullable(); // Chatwoot conversation ID
            $table->string('external_order_id')->nullable(); // WooCommerce/Shopify order ID

            // Metadata
            $table->json('metadata')->nullable(); // Extra data: discount %, original price, etc.
            $table->timestamp('completed_at')->nullable();
            $table->timestamps();

            // Indexes
            $table->index(['company_id', 'status']);
            $table->index(['company_id', 'created_at']);
            $table->index(['company_id', 'product_provider']);
            $table->index('customer_phone');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('sales');
    }
};
